version: '3.7'

services:

  spark-master:
    image: bitnami/spark:3.5.1
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - /path/to/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf

  spark-worker-1:
    image: bitnami/spark:3.5.1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - /path/to/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf

  spark-worker-2: 
    image: bitnami/spark:3.5.1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - /path/to/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf

  jupyterlab:
    image: jupyter/all-spark-notebook:lab-3.5.1
    ports:
      - "8888:8888" # JupyterLab
    volumes:
      - ./data:/hdvm12/datalake # persistent storage
    environment:
      - JUPYTER_ENABLE_LAB=yes

volumes:
  spark-logs:

